CREATE TABLESPACE TS_SHARP_1
    DATAFILE 'C:\app\orcl_wald\tablespaces\TS_SHARP_1.dbf'
    SIZE 20M
    REUSE AUTOEXTEND ON NEXT 2M
    ONLINE
    EXTENT MANAGEMENT LOCAL;
    
CREATE TABLESPACE TS_SHARP_2
    DATAFILE 'C:\app\orcl_wald\tablespaces\TS_SHARP_2.dbf'
    SIZE 20M
    REUSE AUTOEXTEND ON NEXT 2M
    ONLINE
    EXTENT MANAGEMENT LOCAL;
    
CREATE TABLESPACE TS_SHARP_3
    DATAFILE 'C:\app\orcl_wald\tablespaces\TS_SHARP_3.dbf'
    SIZE 20M
    REUSE AUTOEXTEND ON NEXT 2M
    ONLINE
    EXTENT MANAGEMENT LOCAL;
    
CREATE TABLESPACE TS_SHARP_4
    DATAFILE 'C:\app\orcl_wald\tablespaces\TS_SHARP_4.dbf'
    SIZE 20M
    REUSE AUTOEXTEND ON NEXT 2M
    ONLINE
    EXTENT MANAGEMENT LOCAL;
  
CREATE TABLE T_RANGE(
id NUMBER PRIMARY KEY,
value NUMBER,
number_col NUMBER
)
PARTITION BY RANGE (number_col) (
  PARTITION p1 VALUES LESS THAN (5) TABLESPACE TS_SHARP_1,
  PARTITION p2 VALUES LESS THAN (10) TABLESPACE TS_SHARP_2,
  PARTITION p3 VALUES LESS THAN (15) TABLESPACE TS_SHARP_3,
  PARTITION p4 VALUES LESS THAN (MAXVALUE) TABLESPACE TS_SHARP_4
);

INSERT INTO T_RANGE (id, value, number_col)
SELECT 4, 100, 4 FROM DUAL UNION ALL
SELECT 9, 200, 8 FROM DUAL UNION ALL
SELECT 14, 300, 14 FROM DUAL UNION ALL
SELECT 16, 400, 17 FROM DUAL;

SELECT * FROM T_RANGE PARTITION(p1);
SELECT * FROM T_RANGE PARTITION(p4);
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
UPDATE T_RANGE SET number_col = 30 WHERE id = 4;

ALTER TABLE T_RANGE SPLIT PARTITION P1 INTO 
    (PARTITION P1A VALUES LESS THAN (3), 
     PARTITION P1B );
    
CREATE TABLE T_INTERVAL (
  id NUMBER PRIMARY KEY,
  value NUMBER,
  date_col DATE
)
PARTITION BY RANGE (date_col)
INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION p1 VALUES LESS THAN (TO_DATE('01-01-2020', 'DD-MM-YYYY')),
  PARTITION p2 VALUES LESS THAN (TO_DATE('01-02-2020', 'DD-MM-YYYY')),
  PARTITION p3 VALUES LESS THAN (TO_DATE('01-03-2020', 'DD-MM-YYYY'))
); 
INSERT INTO T_INTERVAL (id, value, date_col)
SELECT 1, 100, TO_DATE('2022-01-03', 'YYYY-MM-DD') FROM DUAL UNION ALL
SELECT 2, 200, TO_DATE('2022-02-04', 'YYYY-MM-DD') FROM DUAL UNION ALL
SELECT 3, 300, TO_DATE('2022-03-06', 'YYYY-MM-DD') FROM DUAL UNION ALL
SELECT 4, 400, TO_DATE('2022-04-08', 'YYYY-MM-DD') FROM DUAL;

SELECT * FROM T_INTERVAL PARTITION(p1);
SELECT * FROM T_INTERVAL PARTITION(p3);
ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;
UPDATE T_INTERVAL SET date_col = TO_DATE('2022-05-01', 'YYYY-MM-DD') WHERE id = 2;
    
CREATE TABLE T_HASH (
  id NUMBER PRIMARY KEY,
  varchar_col VARCHAR2(50)
)
PARTITION BY HASH (varchar_col)(
  PARTITION p1 TABLESPACE TS_SHARP_1,
  PARTITION p2 TABLESPACE TS_SHARP_2,
  PARTITION p3 TABLESPACE TS_SHARP_3,
  PARTITION p4 TABLESPACE TS_SHARP_4
)    
INSERT INTO T_HASH (id, varchar_col)
SELECT 1, 'AAA' FROM DUAL UNION ALL
SELECT 2, 'BBB' FROM DUAL UNION ALL
SELECT 3, 'CCC' FROM DUAL UNION ALL
SELECT 4, 'DDD' FROM DUAL;

SELECT * FROM T_HASH PARTITION(p3);
ALTER TABLE T_HASH ENABLE ROW MOVEMENT;
UPDATE T_HASH SET varchar_col = 'EEE' WHERE id = 3;


CREATE TABLE T_LIST (
  id NUMBER PRIMARY KEY,
  char_col CHAR(1)
)
PARTITION BY LIST (char_col)
(
  PARTITION p1 VALUES ('A', 'B') TABLESPACE TS_SHARP_1,
  PARTITION p2 VALUES ('C', 'D') TABLESPACE TS_SHARP_2,
  PARTITION p3 VALUES ('E', 'F') TABLESPACE TS_SHARP_3,
  PARTITION p4 VALUES (DEFAULT) TABLESPACE TS_SHARP_4
);

INSERT INTO T_LIST (id, char_col)
SELECT 1, 'A' FROM DUAL UNION ALL
SELECT 2, 'B' FROM DUAL UNION ALL
SELECT 3, 'C' FROM DUAL UNION ALL
SELECT 4, 'C' FROM DUAL UNION ALL
SELECT 5, 'D' FROM DUAL;

SELECT * FROM T_LIST PARTITION(p1);
ALTER TABLE T_LIST ENABLE ROW MOVEMENT;
UPDATE T_LIST SET char_col = 'D' WHERE id = 1;

ALTER TABLE T_LIST MERGE PARTITIONS p1, p2
INTO PARTITION p12;
SELECT * FROM T_LIST PARTITION(p12);


DROP TABLE T_EXCHANGE
CREATE TABLE T_EXCHANGE (
  ID NUMBER,
  VALUE VARCHAR2(10)
)
PARTITION BY RANGE (VALUE)
(
  PARTITION P1 VALUES LESS THAN ('F'),
  PARTITION P2 VALUES LESS THAN ('M'),
  PARTITION P3 VALUES LESS THAN ('T'),
  PARTITION P4 VALUES LESS THAN (MAXVALUE)
);

-- Вставляем данные в таблицы T_HASH и T_EXCHANGE
INSERT INTO T_HASH VALUES (111, 'aaa');
INSERT INTO T_HASH VALUES (222, 'bbb');
INSERT INTO T_EXCHANGE PARTITION (P1) VALUES (333, 'ccc');
INSERT INTO T_EXCHANGE PARTITION (P3) VALUES (444, 'ddd');

-- Обменяем содержимым секции таблицы T_HASH, содержащей значение ключа секционирования 'aaa', на содержимое таблицы T_EXCHANGE секции P1
ALTER TABLE T_HASH EXCHANGE PARTITION FOR (10) WITH TABLE T_EXCHANGE;

-- Проверяем результат
SELECT * FROM T_HASH;
SELECT * FROM T_EXCHANGE;

SELECT table_name, partitioning_type
FROM user_part_tables;

SELECT partition_name
FROM user_tab_partitions
WHERE table_name = 'T_HASH';

SELECT * FROM T_RANGE PARTITION (p2);

SELECT *
FROM T_INTERVAL
WHERE date_col >= DATE '2023-01-01' AND date_col < DATE '2023-02-01';
